apiVersion: apps/v1
kind: Deployment
metadata:
  name: mychatbot
  labels:
    app: mychatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mychatbot
      azure.workload.identity/use: "true"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mychatbot
        azure.workload.identity/use: "true"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: workload-identity-sa
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: mychatbot
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: mychatbot
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: mychatbot
        image: charliliacr.azurecr.io/mychatbot:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        env:
        - name: TITLE
          value: "My Chatbot"
        - name: LABEL
          value: "Askmeanything"
        - name: TEMPERATURE
          value: "0.9"
        - name: IMAGE_WIDTH
          value: "100"
        - name: AZURE_OPENAI_TYPE
          value: "azure"
        - name: AZURE_OPENAI_BASE
          value: "openai_base"
        - name: AZURE_OPENAI_MODEL
          value: "model"
        - name: AZURE_OPENAI_DEPLOYMENT
          value: "deployment name"
        - name: AZURE_OPENAI_KEY
          value: " "
